name: Open edX Tutor k8s create edx admin user
description: Github Action to create an admin user for Open edX LMS
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namesapce to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    #----------------------------------------------------------------------
    # returns bash environment commands of the form:
    #     export ADMIN_PASSWORD=some-password
    #     export ADMIN_USER=admin
    #     export ADMIN_EMAIL=admin@yourdomain.edu
    #----------------------------------------------------------------------
    - name: fetch secret
      id: get-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1.0.0
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: admin-edx

    - name: Create admin user
      id: create-user
      shell: bash
      run:  tutor k8s do createuser --password "$TUTOR_ADMIN_PASSWORD" --staff --superuser "$TUTOR_ADMIN_USER" "$TUTOR_ADMIN_EMAIL"
